name: flutter_profile_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #flutter_icons: ^3.1.3
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0
  
  
flutter:
  uses-material-design: true

assets:

  - assets/images/goa_maria.jpg

fonts:
  - family: Poppins
    fonts:

    - assets: assets/fonts/Poppins-SemiBold.ttf
      weight: 700
    - assets: assets/fonts/Poppins-Regular.ttf
      weight: 500
    - assets: assets/fonts/Poppins-light.ttf
      weight: 300



